chore(install): renamed variable names for readability
newrelic/newrelic-cli pull request #1026
Opened 2021-07-30 21:30 UTC by noahmmcgivern

2021-07-30 21:31 UTC, ctrombley submitted a review, later dismissed

2021-07-30 22:09 UTC, Julien4218 commented
@noahmmcgivern I was going to review/merge this PR, but the lint job is failing, can you look into it?

2021-07-30 22:09 UTC, Julien4218 requested changes
lint job failing

2021-08-02 21:07 UTC, Julien4218 approved these changes

2021-08-02 21:17 UTC, merged