chore(config): config refactor for simplicity
newrelic/newrelic-cli pull request #605
Opened 2021-01-13 06:00 UTC by ctrombley

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config.go
> +	if ProfileOverride != "" {
Invert if

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config.go
> +		if err := SaveDefaultProfileName(""); err != nil {
Delete the file rather than setting empty string

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config.go
> +		log.Fatalf("%s is required, set it in your default profile or use the %s environment variable", AccountID, f.EnvOverride)
return err here

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config.go
> +		log.Fatalf("%s is required, set it in your default profile or use the %s environment variable", key, f.EnvOverride)
return err here

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config.go
> +		log.Fatalf("%s is required, set it in your default profile or use the %s environment variable", key, f.EnvOverride)
return err here

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config.go
> +	if err := ioutil.WriteFile(defaultProfileFilePath, []byte("\""+profileName+"\""), 0644); err != nil {
prefer 0640

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config.go
> +	return fmt.Sprintf("%s/.newrelic", home), nil
move to const

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config.go
> +func isValidCredentialKey(key ProfileFieldKey) bool {
rename to isValidProfileKey

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config.go
> +func ProfileExists(profile string) bool {
Add godoc to all exported methods

2021-01-20 20:54 UTC, ctrombley commented on internal/config/config_test.go
> +// +build integration
Rename this file to config_integration_test.go

2021-01-20 20:54 UTC, ctrombley commented on internal/edge/command_trace_observer.go
> +	PreRun: func(cmd *cobra.Command, args []string) {
Change to PersistentPreRun.  Validate with command metadata tests (same with others)

2021-01-20 20:54 UTC, ctrombley commented on internal/entities/command_tags.go
> +		utils.LogIfFatal(err)
Get rid of LogIfFatal usage

2021-01-20 20:54 UTC, ctrombley commented on internal/entities/command_tags.go
> +		utils.LogIfFatal(err)
Get rid of LogIfFatal usage

2021-01-20 20:54 UTC, ctrombley commented on internal/entities/command_tags.go
> +		utils.LogIfFatal(err)
Get rid of LogIfFatal usage

2021-01-20 20:54 UTC, ctrombley commented on internal/entities/command_tags.go
> +		utils.LogIfFatal(err)
Get rid of LogIfFatal usage

2021-01-20 20:54 UTC, ctrombley commented on internal/nerdstorage/command.go
> +	PreRun: func(cmd *cobra.Command, args []string) {
Change to PersistentPreRun

2021-01-20 20:54 UTC, ctrombley commented on internal/nrql/command.go
> +	PreRun: func(cmd *cobra.Command, args []string) {
Change to PersistentPreRun

2021-01-20 20:54 UTC, ctrombley commented on internal/profiles/command.go
> +			if e := config.RemoveProfile(profileName); e != nil {
Create update & save commands to cut down on boiler plate

2021-01-20 20:54 UTC, ctrombley commented on internal/profiles/command.go
> +			accountIDVal := config.GetProfileValueInt(n, config.AccountID)
refactor to getAccountID

2021-01-21 21:39 UTC, zlesnr submitted a review, later dismissed

2021-02-03 23:52 UTC, zlesnr approved these changes

2021-07-01 14:41 UTC, Julien4218 requested changes
This work is currently been re-done

2021-07-12 17:46 UTC, ctrombley commented
Duplicate of #948

2021-07-12 17:46 UTC, closed without merging