chore(install): NR CLI Translate base64 encoded urls command #623
newrelic/newrelic-cli pull request #653
Opened 2021-02-01 21:35 UTC by GlenOFoghlu

Created this PR to create Decode CLI operation -> https://github.com/newrelic/newrelic-cli/issues/623

2021-02-01 21:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-cli?pullRequest=653) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-cli?pullRequest=653) before we can accept your contribution.<br/><hr/>**nfoley** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-cli?pullRequest=653) it.</sub>

2021-02-02 16:48 UTC, sanderblue requested changes
This is looking great! I have one suggestion for the command signature now that I understand the desired output of the command.

2021-02-02 16:48 UTC, sanderblue commented on cmd/newrelic/command_decode.go
> +		fmt.Println(decodedURL)
Can we delete these two lines of output? This looks like debugging output 🙂

2021-02-02 16:48 UTC, sanderblue commented on cmd/newrelic/command_decode.go
> +		relicString := strings.Join(args, " ")
Does the empty string need the space? 

i.e. can this
```go
strings.Join(args, " ")
```

be this?
```go
strings.Join(args, "")
```

2021-02-02 16:48 UTC, sanderblue commented on cmd/newrelic/command_decode.go
> +			fmt.Println("\n**** Decoded Entity ID **** ")
Awesome stuff to get this going. I think we can move forward with this, but we might want to adjust the command signature to be a little more declarative. A declarative signature will help us avoid needing the extra line of output to describe what we're displaying. 

Hypothetical command signature:
```zsh
newrelic decode url https://yadda.yadda.com?pane=eyJuZXJk... --param "pane" --search "entityId"
```

This signature allows the user to define what they want from the URL's query param `pane` as well as what to search for in the encoded string. The `--query-param` flag value can then be passed to the function on [line 23](https://github.com/newrelic/newrelic-cli/pull/653/files#diff-90f45227f18dce8728ec5764cfbef896385ae0d17ac97f9b37ff5d6b64bd2c18R23) and the `--search` value can be passed to [line 34](https://github.com/newrelic/newrelic-cli/pull/653/files#diff-90f45227f18dce8728ec5764cfbef896385ae0d17ac97f9b37ff5d6b64bd2c18R34) and [line 38](https://github.com/newrelic/newrelic-cli/pull/653/files#diff-90f45227f18dce8728ec5764cfbef896385ae0d17ac97f9b37ff5d6b64bd2c18R38) (`gjson.Get(decodedURL, decodeSearch)`) or something to that effect. 

This give the user the ability to decode other URL parts as well if/when things change down the line.

2021-02-04 20:42 UTC, closed without merging

2021-02-05 21:09 UTC, zlesnr commented
Thank you for the contribution.